### PR TITLE
feat: add new thumbnaills ds

### PR DESCRIPTION
**Pull request by HMontarroyos**
adding skins and gameplays of new miniatures for the ds ;)

### CODE REVIEW

**Review by RobLoach — CHANGES_REQUESTED** [review]
These look great! Thanks so much. Looks like there are bunch that are greater than 512px wide though. Would you be able to resize the ones that are larger?

**Comment by HMontarroyos** [comment]
Everything OK my friend ? So I'm using retroarch desktop, to be able to
save the thumbnails and it is always saving in that format even when resizing, when I drag and place it there, is there any in particular or something you want me to adjust?
That at first I'm not sure even adjusting when I put it through retroarch desktop it changes the dimensions of the image

**Comment by RobLoach** [comment]
Thumbnails need to be a maximum of 512 pixels wide. https://github.com/libretro-thumbnails/libretro-thumbnails#usage

**Comment by HMontarroyos** [comment]
OK friend, I understand, I felt here and I'm using a program to resize all the images that cross the 512px width limit, I'll upload the updates later and let you know, hug.

**Comment by HMontarroyos** [comment]
adjusted friend @RobLoach , I'm waiting for you ;)

**Review by RobLoach — APPROVED** [review]
Looks great! Thanks so much.

**Pull request merged**
