### PR TITLE
New entries for consistency

### PR DESCRIPTION
**Pull request by masanasake**

### CODE REVIEW

**Comment by MarcoEstevez** [comment]
Children of mana already exists

**Comment by masanasake** [comment]
There is no boxart for only "Children of Mana" despite the snaps and title being there. 
image

**Comment by MarcoEstevez** [comment]
Better to delete Snaps & Titles duplicated entries then, @masanasake will you mind doing it?

**Comment by MarcoEstevez** [comment]
Looks great but why are you adding again nintendogs, starFox and new super Mario bros (USA) region, I though we did fix them :-)

According to retroarch documentation, https://github.com/libretro/libretro-database

_Generally, RetroArch's scanner is configured for ROMs that have been validated by [No-Intro](http://datomatic.no-intro.org/) or Redump DAT files but many other source databases are also in use._

And thus images should name according to it's No-Intro entry, now these 3 roms were called previously only (USA) then the were updated to (USA, Australia) by No-Intro and that is why you found these issues, now I did renamed them to match again with metadata database.

https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Nintendo%20-%20Nintendo%20DS.dat

image


This is the document I always follow to name them, also is a way to validate them, you can go to Information menu --> Database Manager.

My recomendation is for entries that exist on No-Intro we should stick to No-Intro names, now when it comes to hacks, I have no clue, Seems like we tempt to accept them but without an official name convention this would hardly work as every person might have it's own rom name, but let's take it separately :-)

Can you please discard USA entries that exist as (USA, Australia) already, then I think we can merge it :-)

**Comment by masanasake** [comment]
Yeah, the reason I wanted them both was because when scanning the metadata, both existed. I'm not entirely sure how all this works, but if you have control over what these files are recognized as, have you ever considered updating the Wii library to use dashes instead of colons? I can remove USA/Australia in favor of just USA

**Comment by masanasake** [comment]
Pokemon Soulsilver has this Australia issue as well.

**Comment by masanasake** [comment]
Removed the (USA, Australia) entries for these games so only the USA remains.

**Comment by masanasake** [comment]
Ah damn, now that I re-read that, did you mean deleted the USA entries and keep the USA Australia ones? I can fix it again if need be. No big deal.

**Comment by MarcoEstevez** [comment]
Yes sorry, I might not have been clear :-), basically I meant stick to database names, for these particular ones

New Super mario bros, star fox and nintendogs the correct regions are (USA, Australia) so just take them out from your PR

**Comment by masanasake** [comment]
Alright, I think everything is completed for this pull request. Any idea what's holding up my Gamecube one from being committed?

**Comment by MarcoEstevez** [comment]
Looks much better now, one last thing, titles and snaps for Nintendogs - Lab _ Friends (USA, Australia).png and way to big, can you make them 512px wide

As per the other commit, I'll revise it and merge, as far as I remember looked fine :-D

**Comment by masanasake** [comment]
Sorry, didn't even think about resizing. Done. No such luck for the GBA request? :D

**Comment by MarcoEstevez** [comment]
Thanks @masanasake we are done here, let me check your GBA PR

**Pull request merged**
