### PR TITLE
Added missing boxart

### PR DESCRIPTION
**Pull request by Hawaka743**
Added missing boxart for every Yu-Gi-Oh! game and for the 2 versions of "Unsolved Crimes". Also replaced the boxart for Etrian Odyssey's European release, as it was using a cover specific to the German release.

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks for the fixes!

**Comment by MarcoEstevez** [comment]
What was wrong with the German one? I mean, I usually don't really care, but in this specific case, the one replaced has much more better quality.

**Comment by RobLoach** [comment]
Yeah, we'll need one for...
```
Etrian Odyssey (Europe) (En,Fr,De,Es,It)
```
http://datomatic.no-intro.org/index.php?page=show_record&s=28&n=2338

**Comment by Hawaka743** [comment]
The European and German covers for Etrian Odyssey are technically the same, except the age restriction label. I don't mind prioritizing quality over correctness in this case. Should a change it back.

I don't think I understand RobLoach's comment.

**Pull request merged**
