### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by MarcoEstevez**
Rename box region, add the missing region, improvements and a missing box

### CODE REVIEW

**Comment by RobLoach** [comment]
I see they're 514 pixels wide? Should be 512. May effect scaling in RA.

**Comment by MarcoEstevez** [comment]
Ill fix it

**Comment by MarcoEstevez** [comment]
Could you please provide an example, I did revise the 100 images, but I could'n find one with more than 512px wide

**Comment by RobLoach** [comment]
My bad! My browser was zoomed in hahahaa. Well done! :+1:

**Pull request merged**
